apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "oidc-guard.fullname" . }}
  labels:
    {{- include "oidc-guard.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "oidc-guard.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "oidc-guard.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "oidc-guard.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          {{- if .Values.settings.cookie.clientSecretName }}
          - name: settings__cookie__clientSecret
            valueFrom:
              secretKeyRef:
                name: {{ .Values.settings.cookie.clientSecretName }}
                key: {{ .Values.settings.cookie.clientSecretKey }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp-volume
            - name: appsettings-volume
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
              readOnly: true
            {{- if .Values.settings.sslCertSecretName }}
            - name: appsettings-ssl
              mountPath: /app/ssl/
              readOnly: true
            {{- end }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
        - name: appsettings-volume
          secret:
            secretName: {{ include "oidc-guard.fullname" . }}
        {{- if .Values.settings.sslCertSecretName }}
        - name: appsettings-ssl
          secret:
            secretName: "{{ .Values.settings.sslCertSecretName }}"
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
