apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "oidc-guard.fullname" . }}
  labels:
    {{- include "oidc-guard.labels" . | nindent 4 }}
spec:
{{- if .Values.storageClassName }}
  storageClassName: {{ .Values.storageClassName }}
{{- end }}
  accessModes:
    - {{ .Values.storageAccessMode }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}