apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oidc-guard.fullname" . }}
  labels:
    {{- include "oidc-guard.labels" . | nindent 4 }}
data:
  appsettings.Production.json: {{ dict "settings" .Values.settings | toJson | b64enc | quote }}