apiVersion: v1
kind: Service
metadata:
  name: {{ include "oidc-guard.fullname" . }}
  labels:
    {{- include "oidc-guard.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.settings.sslCertSecretName }}
    - port: {{ .Values.service.sslPort }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
  selector:
    {{- include "oidc-guard.selectorLabels" . | nindent 4 }}
